### ISSUE TITLE
修改架构图

### ISSUE THREAD

**Issue by zhangzwwww** [zhangzwwww/SE-finalwork#34]
![image](https://user-images.githubusercontent.com/27809927/94557973-e6c33b80-0291-11eb-83db-eb494ef8be9f.png)

修改下架构图，看看有什么问题。 #7

**Comment by YUYUN-ZHAO** [comment]
LGTM

**Comment by lee-vius** [comment]
👍 有没有配套的每一层的解释？

**Comment by zhangzwwww** [comment]
> 👍 有没有配套的每一层的解释？

我在文档里介绍下
